name: lint for py file
on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout or clone
        uses: actions/checkout@v4
        
      - name: install linter
        run: pip install ruff
        
      - name: chekcing the code
        run: ruff check .
