name: lint for py file
on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout or clone
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your preferred version
          cache: 'pip'
        
      - name: install linter
        run: pip install ruff
        
      - name: chekcing the code
        run: ruff check .
